In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
import math
%matplotlib inline

# loading dataset

In [22]:
train = pd.read_csv("C:/Users/pekat/.kaggle/competitions/titanic/train.csv")
test = pd.read_csv("C:/Users/pekat/.kaggle/competitions/titanic/test.csv")
out_sample = pd.read_csv("C:/Users/pekat/.kaggle/competitions/titanic/gender_submission.csv")

In [23]:
X_train = train.drop(["Survived"], axis=1)
y_train = train["Survived"]
X_train.columns, test.columns
X_test = test

# data cleaning

normalize cabin before sklearn pipeline
because sklearn cannot dealing well with array containing nan and object

In [24]:
def append_normalized_cabin(data):
    cabins = X_train["Cabin"]
    cabin_notnull = cabins.notnull()
    cabins = cabins[cabin_notnull].apply(lambda x: ord(x[0])) - ord("A")
    data.loc[cabin_notnull, "CabinNorm"] = cabins

In [25]:
append_normalized_cabin(X_train)
append_normalized_cabin(X_test)

In [26]:
X_train.fillna("NaN")
X_test.fillna("NaN")

PassengerId  Pclass                                               Name  \
0            892       3                                   Kelly, Mr. James   
1            893       3                   Wilkes, Mrs. James (Ellen Needs)   
2            894       2                          Myles, Mr. Thomas Francis   
3            895       3                                   Wirz, Mr. Albert   
4            896       3       Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
5            897       3                         Svensson, Mr. Johan Cervin   
6            898       3                               Connolly, Miss. Kate   
7            899       2                       Caldwell, Mr. Albert Francis   
8            900       3          Abrahim, Mrs. Joseph (Sophie Halaut Easu)   
9            901       3                            Davies, Mr. John Samuel   
10           902       3                                   Ilieff, Mr. Ylio   
11           903       1                         Jones, Mr. Charles Cresson   
12           904       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)   
13           905       2                               Howard, Mr. Benjamin   
14           906       1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...   
15           907       2      del Carlo, Mrs. Sebastiano (Argenia Genovesi)   
16           908       2                                  Keane, Mr. Daniel   
17           909       3                                  Assaf, Mr. Gerios   
18           910       3                       Ilmakangas, Miss. Ida Livija   
19           911       3              Assaf Khalil, Mrs. Mariana (Miriam")"   
20           912       1                             Rothschild, Mr. Martin   
21           913       3                          Olsen, Master. Artur Karl   
22           914       1               Flegenheim, Mrs. Alfred (Antoinette)   
23           915       1                    Williams, Mr. Richard Norris II   
24           916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
25           917       3                            Robins, Mr. Alexander A   
26           918       1                       Ostby, Miss. Helene Ragnhild   
27           919       3                                  Daher, Mr. Shedid   
28           920       1                            Brady, Mr. John Bertram   
29           921       3                                  Samaan, Mr. Elias   
..           ...     ...                                                ...   
388         1280       3                               Canavan, Mr. Patrick   
389         1281       3                        Palsson, Master. Paul Folke   
390         1282       1                         Payne, Mr. Vivian Ponsonby   
391         1283       1     Lines, Mrs. Ernest H (Elizabeth Lindsey James)   
392         1284       3                      Abbott, Master. Eugene Joseph   
393         1285       2                               Gilbert, Mr. William   
394         1286       3                           Kink-Heilmann, Mr. Anton   
395         1287       1     Smith, Mrs. Lucien Philip (Mary Eloise Hughes)   
396         1288       3                               Colbert, Mr. Patrick   
397         1289       1  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...   
398         1290       3                     Larsson-Rondberg, Mr. Edvard A   
399         1291       3                           Conlon, Mr. Thomas Henry   
400         1292       1                            Bonnell, Miss. Caroline   
401         1293       2                                    Gale, Mr. Harry   
402         1294       1                     Gibson, Miss. Dorothy Winifred   
403         1295       1                             Carrau, Mr. Jose Pedro   
404         1296       1                       Frauenthal, Mr. Isaac Gerald   
405         1297       2       Nourney, Mr. Alfred (Baron von Drachstedt")"   
406         1298       2                          Ware,

In [8]:
X_train

PassengerId  Pclass                                               Name  \
0              1       3                            Braund, Mr. Owen Harris   
1              2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2              3       3                             Heikkinen, Miss. Laina   
3              4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4              5       3                           Allen, Mr. William Henry   
5              6       3                                   Moran, Mr. James   
6              7       1                            McCarthy, Mr. Timothy J   
7              8       3                     Palsson, Master. Gosta Leonard   
8              9       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)   
9             10       2                Nasser, Mrs. Nicholas (Adele Achem)   
10            11       3                    Sandstrom, Miss. Marguerite Rut   
11            12       1                           Bonnell, Miss. Elizabeth   
12            13       3                     Saundercock, Mr. William Henry   
13            14       3                        Andersson, Mr. Anders Johan   
14            15       3               Vestrom, Miss. Hulda Amanda Adolfina   
15            16       2                   Hewlett, Mrs. (Mary D Kingcome)    
16            17       3                               Rice, Master. Eugene   
17            18       2                       Williams, Mr. Charles Eugene   
18            19       3  Vander Planke, Mrs. Julius (Emelia Maria Vande...   
19            20       3                            Masselmani, Mrs. Fatima   
20            21       2                               Fynney, Mr. Joseph J   
21            22       2                              Beesley, Mr. Lawrence   
22            23       3                        McGowan, Miss. Anna "Annie"   
23            24       1                       Sloper, Mr. William Thompson   
24            25       3                      Palsson, Miss. Torborg Danira   
25            26       3  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...   
26            27       3                            Emir, Mr. Farred Chehab   
27            28       1                     Fortune, Mr. Charles Alexander   
28            29       3                      O'Dwyer, Miss. Ellen "Nellie"   
29            30       3                                Todoroff, Mr. Lalio   
..           ...     ...                                                ...   
861          862       2                        Giles, Mr. Frederick Edward   
862          863       1  Swift, Mrs. Frederick Joel (Margaret Welles Ba...   
863          864       3                  Sage, Miss. Dorothy Edith "Dolly"   
864          865       2                             Gill, Mr. John William   
865          866       2                           Bystrom, Mrs. (Karolina)   
866          867       2                       Duran y More, Miss. Asuncion   
867          868       1               Roebling, Mr. Washington Augustus II   
868          869       3                        van Melkebeke, Mr. Philemon   
869          870       3                    Johnson, Master. Harold Theodor   
870          871       3                                  Balkic, Mr. Cerin   
871          872       1   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)   
872          873       1                           Carlsson, Mr. Frans Olof   
873          874       3                        Vander Cruyssen, Mr. Victor   
874          875       2              Abelson, Mrs. Samuel (Hannah Wizosky)   
875          876       3                   Najib, Miss. Adele Kiamie "Jane"   
876          877       3                      Gustafsson, Mr. Alfred Ossian   
877          878       3                               Petroff, Mr. Nedelio   
878          879       3                                 Laleff, Mr. Kristo   
879          880       1      Potter, Mrs. Thomas Jr (L

In [9]:
from sklearn.base import BaseEstimator, TransformerMixin

class DataFrameSelector(BaseEstimator, TransformerMixin):
    def __init__(self, attribute_names):
        self.attribute_names = attribute_names
        
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[self.attribute_names].values

define upcoming CategoricalEncoder

In [10]:
# Definition of the CategoricalEncoder class, copied from PR #9151.
# Just run this cell, or copy it to your code, do not try to understand it (yet).

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.utils import check_array
from sklearn.preprocessing import LabelEncoder
from scipy import sparse

class CategoricalEncoder(BaseEstimator, TransformerMixin):
    """Encode categorical features as a numeric array.
    The input to this transformer should be a matrix of integers or strings,
    denoting the values taken on by categorical (discrete) features.
    The features can be encoded using a one-hot aka one-of-K scheme
    (``encoding='onehot'``, the default) or converted to ordinal integers
    (``encoding='ordinal'``).
    This encoding is needed for feeding categorical data to many scikit-learn
    estimators, notably linear models and SVMs with the standard kernels.
    Read more in the :ref:`User Guide <preprocessing_categorical_features>`.
    Parameters
    ----------
    encoding : str, 'onehot', 'onehot-dense' or 'ordinal'
        The type of encoding to use (default is 'onehot'):
        - 'onehot': encode the features using a one-hot aka one-of-K scheme
          (or also called 'dummy' encoding). This creates a binary column for
          each category and returns a sparse matrix.
        - 'onehot-dense': the same as 'onehot' but returns a dense array
          instead of a sparse matrix.
        - 'ordinal': encode the features as ordinal integers. This results in
          a single column of integers (0 to n_categories - 1) per feature.
    categories : 'auto' or a list of lists/arrays of values.
        Categories (unique values) per feature:
        - 'auto' : Determine categories automatically from the training data.
        - list : ``categories[i]`` holds the categories expected in the ith
          column. The passed categories are sorted before encoding the data
          (used categories can be found in the ``categories_`` attribute).
    dtype : number type, default np.float64
        Desired dtype of output.
    handle_unknown : 'error' (default) or 'ignore'
        Whether to raise an error or ignore if a unknown categorical feature is
        present during transform (default is to raise). When this is parameter
        is set to 'ignore' and an unknown category is encountered during
        transform, the resulting one-hot encoded columns for this feature
        will be all zeros.
        Ignoring unknown categories is not supported for
        ``encoding='ordinal'``.
    Attributes
    ----------
    categories_ : list of arrays
        The categories of each feature determined during fitting. When
        categories were specified manually, this holds the sorted categories
        (in order corresponding with output of `transform`).
    Examples
    --------
    Given a dataset with three features and two samples, we let the encoder
    find the maximum value per feature and transform the data to a binary
    one-hot encoding.
    >>> from sklearn.preprocessing import CategoricalEncoder
    >>> enc = CategoricalEncoder(handle_unknown='ignore')
    >>> enc.fit([[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2]])
    ... # doctest: +ELLIPSIS
    CategoricalEncoder(categories='auto', dtype=<... 'numpy.float64'>,
              encoding='onehot', handle_unknown='ignore')
    >>> enc.transform([[0, 1, 1], [1, 0, 4]]).toarray()
    array([[ 1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.],
           [ 0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.]])
    See also
    --------
    sklearn.preprocessing.OneHotEncoder : performs a one-hot encoding of
      integer ordinal features. The ``OneHotEncoder assumes`` that input
      features take on values in the range ``[0, max(feature)]`` instead of
      using the unique values.
    sklearn.feature_extraction.DictVectorizer : performs a one-hot encoding of
      dictionary items (also handles string-valued features).
    sklearn.feature_extraction.FeatureHasher : performs an approximate one-hot
      encoding of dictionary items or strings.
    """

    def __init__(self, encoding='onehot', categories='auto', dtype=np.float64,
                 handle_unknown='error'):
        self.encoding = encoding
        self.categories = categories
        self.dtype = dtype
        self.handle_unknown = handle_unknown

    def fit(self, X, y=None):
        """Fit the CategoricalEncoder to X.
        Parameters
        ----------
        X : array-like, shape [n_samples, n_feature]
            The data to determine the categories of each feature.
        Returns
        -------
        self
        """

        if self.encoding not in ['onehot', 'onehot-dense', 'ordinal']:
            template = ("encoding should be either 'onehot', 'onehot-dense' "
                        "or 'ordinal', got %s")
            raise ValueError(template % self.handle_unknown)

        if self.handle_unknown not in ['error', 'ignore']:
            template = ("handle_unknown should be either 'error' or "
                        "'ignore', got %s")
            raise ValueError(template % self.handle_unknown)

        if self.encoding == 'ordinal' and self.handle_unknown == 'ignore':
            raise ValueError("handle_unknown='ignore' is not supported for"
                             " encoding='ordinal'")

        X = check_array(X, dtype=np.object, accept_sparse='csc', copy=True)
        n_samples, n_features = X.shape

        self._label_encoders_ = [LabelEncoder() for _ in range(n_features)]

        for i in range(n_features):
            le = self._label_encoders_[i]
            Xi = X[:, i]
            if self.categories == 'auto':
                le.fit(Xi)
            else:
                valid_mask = np.in1d(Xi, self.categories[i])
                if not np.all(valid_mask):
                    if self.handle_unknown == 'error':
                        diff = np.unique(Xi[~valid_mask])
                        msg = ("Found unknown categories {0} in column {1}"
                               " during fit".format(diff, i))
                        raise ValueError(msg)
                le.classes_ = np.array(np.sort(self.categories[i]))

        self.categories_ = [le.classes_ for le in self._label_encoders_]

        return self

    def transform(self, X):
        """Transform X using one-hot encoding.
        Parameters
        ----------
        X : array-like, shape [n_samples, n_features]
            The data to encode.
        Returns
        -------
        X_out : sparse matrix or a 2-d array
            Transformed input.
        """
        X = check_array(X, accept_sparse='csc', dtype=np.object, copy=True)
        n_samples, n_features = X.shape
        X_int = np.zeros_like(X, dtype=np.int)
        X_mask = np.ones_like(X, dtype=np.bool)

        for i in range(n_features):
            valid_mask = np.in1d(X[:, i], self.categories_[i])

            if not np.all(valid_mask):
                if self.handle_unknown == 'error':
                    diff = np.unique(X[~valid_mask, i])
                    msg = ("Found unknown categories {0} in column {1}"
                           " during transform".format(diff, i))
                    raise ValueError(msg)
                else:
                    # Set the problematic rows to an acceptable value and
                    # continue `The rows are marked `X_mask` and will be
                    # removed later.
                    X_mask[:, i] = valid_mask
                    X[:, i][~valid_mask] = self.categories_[i][0]
            X_int[:, i] = self._label_encoders_[i].transform(X[:, i])

        if self.encoding == 'ordinal':
            return X_int.astype(self.dtype, copy=False)

        mask = X_mask.ravel()
        n_values = [cats.shape[0] for cats in self.categories_]
        n_values = np.array([0] + n_values)
        indices = np.cumsum(n_values)

        column_indices = (X_int + indices[:-1]).ravel()[mask]
        row_indices = np.repeat(np.arange(n_samples, dtype=np.int32),
                                n_features)[mask]
        data = np.ones(n_samples * n_features)[mask]

        out = sparse.csc_matrix((data, (row_indices, column_indices)),
                                shape=(n_samples, indices[-1]),
                                dtype=self.dtype).tocsr()
        if self.encoding == 'onehot-dense':
            return out.toarray()
        else:
            return out

In [11]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, Imputer
from sklearn.pipeline import FeatureUnion

num_pipeline = Pipeline([
    ("selector", DataFrameSelector(["Pclass", "Age", "SibSp", "Parch", "Fare", "CabinNorm"])),
    ("imputer", Imputer(strategy="median")),
    ("std_scaler", StandardScaler()),
])

cat_pipeline = Pipeline([
    ("selector", DataFrameSelector(["Sex"])),
    ("label_binarizer", CategoricalEncoder(encoding="onehot-dense")),
])

full_pipeline = FeatureUnion(transformer_list=[
    ("num_pipeline", num_pipeline),
    ("cat_pipeline", cat_pipeline),
])

In [12]:
X_train_prepared = full_pipeline.fit_transform(X_train)
X_train_prepared

array([[ 0.82737724, -0.56573646,  0.43279337, ..., -0.11419157,
         0.        ,  1.        ],
       [-1.56610693,  0.66386103,  0.43279337, ..., -0.11419157,
         1.        ,  0.        ],
       [ 0.82737724, -0.25833709, -0.4745452 , ..., -0.11419157,
         1.        ,  0.        ],
       ...,
       [ 0.82737724, -0.1046374 ,  0.43279337, ..., -0.11419157,
         1.        ,  0.        ],
       [-1.56610693, -0.25833709, -0.4745452 , ..., -0.11419157,
         0.        ,  1.        ],
       [ 0.82737724,  0.20276197, -0.4745452 , ..., -0.11419157,
         0.        ,  1.        ]])

# build model

In [13]:
from sklearn.model_selection import cross_val_predict, cross_val_score
from sklearn.ensemble import RandomForestClassifier

forest_clf = RandomForestClassifier(random_state=56)
y_probas_forest = cross_val_score(forest_clf, X_train_prepared, y_train, cv=5)
y_probas_forest

array([0.74860335, 0.80446927, 0.8258427 , 0.76966292, 0.84745763])

In [14]:
def plot_roc_curve(fpr, tpr, label=None):
    plt.plot(fpr, tpr, linewidth=2, label=label)
    plt.plot([0, 1], [0, 1], 'k--')
    plt.axis([0, 1, 0, 1])
    plt.xlabel('false positive rate')
    plt.ylabel('true positive rate')

In [15]:
from sklearn.metrics import roc_curve

fpr, tpr, thresholds = roc_curve(y_train, y_probas_forest)
plot_roc_curve(fpr, tpr, "Random Forest")
plt.legend(loc="lower right")
plt.show()

ValueError: Found input variables with inconsistent numbers of samples: [891, 5]

In [16]:
from sklearn.model_selection import RandomizedSearchCV
parameters = {
        'n_estimators'      : [5, 10, 20, 30, 50, 100, 300],
        'max_features'      : [3, 5, 8],
        'random_state'      : [0],
        'n_jobs'            : [1],
        'min_samples_split' : [3, 5, 10, 15, 20, 25, 30, 40, 50, 100],
        'max_depth'         : [3, 5, 10, 15, 20, 25, 30, 40, 50, 100]
}

clf = RandomizedSearchCV(RandomForestClassifier(), parameters)
clf.fit(X_train_prepared, y_train)

RandomizedSearchCV(cv=None, error_score='raise',
          estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
          fit_params=None, iid=True, n_iter=10, n_jobs=1,
          param_distributions={'n_estimators': [5, 10, 20, 30, 50, 100, 300], 'max_features': [3, 5, 8], 'random_state': [0], 'n_jobs': [1], 'min_samples_split': [3, 5, 10, 15, 20, 25, 30, 40, 50, 100], 'max_depth': [3, 5, 10, 15, 20, 25, 30, 40, 50, 100]},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          return_train_score='warn', scoring=None, verbose=0)

In [17]:
cvres = clf.cv_results_
for mean_score, params in zip(cvres["mean_test_score"], cvres["params"]):
    print(mean_score,  params)

0.8103254769921436 {'random_state': 0, 'n_jobs': 1, 'n_estimators': 300, 'min_samples_split': 50, 'max_features': 8, 'max_depth': 30}
0.8170594837261503 {'random_state': 0, 'n_jobs': 1, 'n_estimators': 20, 'min_samples_split': 20, 'max_features': 3, 'max_depth': 30}
0.8148148148148148 {'random_state': 0, 'n_jobs': 1, 'n_estimators': 30, 'min_samples_split': 25, 'max_features': 8, 'max_depth': 25}
0.8092031425364759 {'random_state': 0, 'n_jobs': 1, 'n_estimators': 10, 'min_samples_split': 5, 'max_features': 8, 'max_depth': 15}
0.819304152637486 {'random_state': 0, 'n_jobs': 1, 'n_estimators': 300, 'min_samples_split': 25, 'max_features': 8, 'max_depth': 10}
0.7822671156004489 {'random_state': 0, 'n_jobs': 1, 'n_estimators': 100, 'min_samples_split': 100, 'max_features': 5, 'max_depth': 20}
0.8170594837261503 {'random_state': 0, 'n_jobs': 1, 'n_estimators': 20, 'min_samples_split': 5, 'max_features': 5, 'max_depth': 10}
0.7833894500561167 {'random_state': 0, 'n_jobs': 1, 'n_estimators': 

In [18]:
best_clf = clf.best_estimator_

In [27]:
X_test_prepared = full_pipeline.fit_transform(X_test)
X_test_prepared

array([[ 0.87348191,  0.38623105, -0.49947002, ..., -0.14038222,
         0.        ,  1.        ],
       [ 0.87348191,  1.37137004,  0.61699237, ..., -0.14038222,
         1.        ,  0.        ],
       [-0.31581919,  2.55353683, -0.49947002, ..., -0.14038222,
         0.        ,  1.        ],
       ...,
       [ 0.87348191,  0.70147553, -0.49947002, ..., -0.14038222,
         0.        ,  1.        ],
       [ 0.87348191, -0.20485235, -0.49947002, ..., -0.14038222,
         0.        ,  1.        ],
       [ 0.87348191, -0.20485235,  0.61699237, ..., -0.14038222,
         0.        ,  1.        ]])

In [28]:
predicted = best_clf.predict(X_test_prepared)
out = test[["PassengerId"]]
out["Survived"] = predicted

C:\Users\pekat\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [29]:
out.to_csv("./first_submission.csv", index=False)

In [34]:
pd.read_csv("./first_submission_fixed.csv").columns == pd.read_csv("./first_submission.csv").columns


array([ True,  True])